version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    open-pull-requests-limit: 4
    schedule:
      interval: weekly
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - 'minor'
          - 'patch'
