name: 'build and test'
on:
  pull_request:
    branches:
    - main
jobs:
  build-and-test:
    name: 'build and test'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.21.0'
      - name: 'build'
        run: go build ./...
      - name: 'test'
        run: go test -cover -v ./...
