---
name: conventional-commit validation
on:
  pull_request_target:
    types:
      - opened
      - edited
      - ready_for_review

permissions:
  pull-requests: read

jobs:
  validate-title:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          ignoreLabels: |
            autorelease: pending
            autorelease: tagged
