name: pre-commit

on:
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '^1.21.0'
      - run: |
          go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.5.0
          go install github.com/go-critic/go-critic/cmd/go-critic@v0.13.0
      - uses: pre-commit/action@v3.0.1
