name: pre-commit

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '^1.21.0'
      - run: |
          go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest
          go install golang.org/x/tools/cmd/goimports@latest
      - uses: pre-commit/action@v3.0.1
